import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // 1. Users Table
  users: defineTable({
    id: v.string(),
    name: v.string(),
    phone: v.string(),
    email: v.optional(v.string()),
    avatar: v.string(),
    role: v.union(v.literal("adopter"), v.literal("owner"), v.literal("shelter"), v.literal("admin")),
    location: v.string(),
    isVerified: v.boolean(),
    joinedDate: v.string(),
    homeType: v.optional(v.string()),
    hasYard: v.optional(v.boolean()),
    otherPets: v.optional(v.string()),
    experienceLevel: v.optional(v.string()),
    bio: v.optional(v.string()),
  }).index("by_user_id", ["id"]).index("by_phone", ["phone"]),

  // 2. Dogs Table
  dogs: defineTable({
    id: v.string(),
    name: v.string(),
    breed: v.string(),
    age: v.string(),
    gender: v.union(v.literal("Male"), v.literal("Female")),
    size: v.union(v.literal("Small"), v.literal("Medium"), v.literal("Large"), v.literal("Extra Large")),
    energy: v.union(v.literal("Low (Couch Potato)"), v.literal("Moderate"), v.literal("High Energy"), v.literal("Zoomies Master")),
    location: v.string(),
    lat: v.number(),
    lng: v.number(),
    city: v.string(),
    state: v.optional(v.string()),
    coverPhoto: v.string(),
    photos: v.array(v.string()),
    bio: v.string(),
    reasonForAdoption: v.string(),
    adoptionType: v.union(v.literal("Free Adoption"), v.literal("Adoption Fee")),
    status: v.union(
      v.literal("available"),
      v.literal("pending"),
      v.literal("meet_scheduled"),
      v.literal("agreement_pending"),
      v.literal("handover_pending"),
      v.literal("adopted")
    ),
    currentOwnerId: v.string(),
    currentOwnerName: v.string(),
    currentOwnerAvatar: v.string(),
    currentOwnerPhone: v.optional(v.string()),
    isOwnerVerified: v.boolean(),
    vaccinated: v.boolean(),
    neutered: v.boolean(),
    microchipped: v.boolean(),
    medicalNotes: v.string(),
    favoriteThings: v.array(v.string()),
    personalityTraits: v.array(v.string()),
    interestedCount: v.number(),
    likesCount: v.number(),
    previousOwnerId: v.optional(v.string()),
    previousOwnerName: v.optional(v.string()),
    newOwnerId: v.optional(v.string()),
    newOwnerName: v.optional(v.string()),
    adoptedDate: v.optional(v.string()),
    certificateId: v.optional(v.string()),
  }).index("by_status", ["status"]).index("by_owner", ["currentOwnerId"]),

  // 3. Adoption Applications Table
  applications: defineTable({
    id: v.string(),
    dogId: v.string(),
    dogName: v.string(),
    dogPhoto: v.string(),
    dogBreed: v.string(),
    applicantId: v.string(),
    applicantName: v.string(),
    applicantAvatar: v.string(),
    applicantLocation: v.string(),
    applicantLat: v.optional(v.number()),
    applicantLng: v.optional(v.number()),
    applicantPhone: v.string(),
    applicantEmail: v.string(),
    reason: v.string(),
    homeType: v.string(),
    hasYard: v.boolean(),
    otherPets: v.string(),
    experienceWithDogs: v.string(),
    vetCareAgreement: v.boolean(),
    workSchedule: v.string(),
    preferredMeetDate: v.string(),
    status: v.union(v.literal("submitted"), v.literal("accepted"), v.literal("declined"), v.literal("completed")),
    declineReason: v.optional(v.string()),
    submittedAt: v.string(),
    reviewedAt: v.optional(v.string()),
  }).index("by_dog", ["dogId"]).index("by_applicant", ["applicantId"]),

  // 4. Conversations & Messages
  conversations: defineTable({
    id: v.string(),
    dogId: v.string(),
    dogName: v.string(),
    dogAvatar: v.string(),
    participants: v.array(v.string()),
    lastMessage: v.string(),
    lastMessageTimestamp: v.string(),
    unreadCount: v.number(),
  }).index("by_dog", ["dogId"]),

  messages: defineTable({
    id: v.string(),
    conversationId: v.string(),
    senderId: v.string(),
    senderName: v.string(),
    senderAvatar: v.string(),
    recipientId: v.string(),
    text: v.string(),
    image: v.optional(v.string()),
    isDogBark: v.optional(v.boolean()),
    timestamp: v.string(),
    read: v.boolean(),
  }).index("by_conversation", ["conversationId"]),

  // 5. Meetups Table
  meetups: defineTable({
    id: v.string(),
    applicationId: v.string(),
    dogId: v.string(),
    dogName: v.string(),
    ownerId: v.string(),
    adopterId: v.string(),
    date: v.string(),
    time: v.string(),
    locationName: v.string(),
    locationAddress: v.string(),
    notes: v.string(),
    status: v.union(v.literal("scheduled"), v.literal("completed"), v.literal("cancelled")),
  }).index("by_application", ["applicationId"]),

  // 6. Agreements Table
  agreements: defineTable({
    id: v.string(),
    applicationId: v.string(),
    dogId: v.string(),
    dogName: v.string(),
    dogBreed: v.string(),
    currentOwnerId: v.string(),
    currentOwnerName: v.string(),
    adopterId: v.string(),
    adopterName: v.string(),
    adoptionDate: v.string(),
    termsAccepted: v.boolean(),
    ownerSignature: v.optional(v.string()),
    ownerSignedAt: v.optional(v.string()),
    adopterSignature: v.optional(v.string()),
    adopterSignedAt: v.optional(v.string()),
    isFullySigned: v.boolean(),
  }).index("by_application", ["applicationId"]),

  // 7. Handovers Table
  handovers: defineTable({
    id: v.string(),
    applicationId: v.string(),
    dogId: v.string(),
    ownerConfirmed: v.boolean(),
    ownerConfirmedAt: v.optional(v.string()),
    adopterConfirmed: v.boolean(),
    adopterConfirmedAt: v.optional(v.string()),
    isCompleted: v.boolean(),
    completedAt: v.optional(v.string()),
  }).index("by_application", ["applicationId"]),
});
